// Generated by CoffeeScript 1.8.0
(function() {
  var Task, TaskView, task, taskView;

  Task = Backbone.Model.extend({
    defaults: {
      title: "do something!",
      completed: false
    }
  });

  task = new Task({
    completed: true
  });

  TaskView = Backbone.View.extend({
    tagName: 'li'
  });

  taskView = new TaskView({
    model: task
  });

  console.log(taskView.el);

  console.log(taskView.$el);

}).call(this);

//# sourceMappingURL=app.js.map
