// Generated by CoffeeScript 1.8.0
(function() {
  var Task, TaskView, task, taskView;

  Task = Backbone.Model.extend({
    defaults: {
      title: "do something!",
      completed: false
    }
  });

  task = new Task({
    completed: true
  });

  TaskView = Backbone.View.extend({
    tagName: 'li',
    events: {
      "click .command": "sayHello"
    },
    sayHello: function() {
      alert('hello!');
    },
    template: _.template($('#task-template').html()),
    render: function() {
      var template;
      template = this.template(this.model.toJSON());
      this.$el.html(template);
      return this;
    }
  });

  taskView = new TaskView({
    model: task
  });

  console.log(taskView.render().el);

  $('body').append(taskView.render().el);

}).call(this);

//# sourceMappingURL=app.js.map
