// Generated by CoffeeScript 1.8.0
var Tasks,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Tasks = (function(_super) {
  __extends(Tasks, _super);

  function Tasks() {
    return Tasks.__super__.constructor.apply(this, arguments);
  }

  Tasks.prototype.model = Task;

  return Tasks;

})(Backbone.Collection);

//# sourceMappingURL=collections.js.map
