// Generated by CoffeeScript 1.8.0
var TaskCollection,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

TaskCollection = (function(_super) {
  __extends(TaskCollection, _super);

  function TaskCollection() {
    return TaskCollection.__super__.constructor.apply(this, arguments);
  }

  TaskCollection.prototype.model = Task;

  return TaskCollection;

})(Backbone.Collection);

//# sourceMappingURL=collections.js.map
