// Generated by CoffeeScript 1.8.0
var Task,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Task = (function(_super) {
  __extends(Task, _super);

  function Task() {
    return Task.__super__.constructor.apply(this, arguments);
  }

  Task.prototype.defaults = {
    title: 'do something',
    completed: false
  };

  Task.prototype.validate = function(attrs) {
    if (_.isEmpty(attrs.title)) {
      return 'title must not be empty!';
    }
  };

  Task.prototype.initialize = function() {
    this.on('invalid', function(model, error) {
      $('#error').html(error);
    });
  };

  return Task;

})(Backbone.Model);

//# sourceMappingURL=models.js.map
